#!/usr/bin/env python3
"""Sync the app-side SKILL.md playbooks into knowledge/skills/*.md.

The canonical source lives at `app/src/main/assets/skills/<name>/SKILL.md`
— the Android SkillRegistry loads them from there on demand. This
script copies each into `knowledge/skills/<name>.md` so the MCP corpus
can expose them via `list_topics()` / `read_doc("skills", name)`.

Two modes:
- `--write` (default): write the destination files, creating
  knowledge/skills/ if needed. Idempotent.
- `--check`: exit non-zero if the destination is out of sync with the
  source. Used by CI (mcp-python.yml) to prevent drift.

Mirrors the pattern used by VerifyExecuteCommandSchemaTask
(buildSrc/src/main/kotlin/schema/SchemaTasks.kt).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HEADER_TEMPLATE = (
    "<!-- Auto-generated by mcp-server/scripts/sync_skills.py from "
    "app/src/main/assets/skills/{name}/SKILL.md — edit the source, not this copy. -->\n"
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def source_skills_dir(root: Path) -> Path:
    return root / "app" / "src" / "main" / "assets" / "skills"


def dest_skills_dir(root: Path) -> Path:
    return root / "knowledge" / "skills"


def discover_skills(src: Path) -> list[tuple[str, Path]]:
    if not src.is_dir():
        return []
    out: list[tuple[str, Path]] = []
    for entry in sorted(src.iterdir()):
        if not entry.is_dir():
            continue
        skill_md = entry / "SKILL.md"
        if skill_md.is_file():
            out.append((entry.name, skill_md))
    return out


def rendered_body(name: str, source: Path) -> str:
    return HEADER_TEMPLATE.format(name=name) + source.read_text(encoding="utf-8")


def sync(check_only: bool) -> int:
    root = repo_root()
    src = source_skills_dir(root)
    dst = dest_skills_dir(root)
    skills = discover_skills(src)
    if not skills:
        print(f"no SKILL.md files found under {src}", file=sys.stderr)
        return 1

    stale: list[str] = []
    if not check_only:
        dst.mkdir(parents=True, exist_ok=True)

    for name, source_path in skills:
        target_path = dst / f"{name}.md"
        expected = rendered_body(name, source_path)
        if check_only:
            if not target_path.is_file() or target_path.read_text(encoding="utf-8") != expected:
                stale.append(name)
        else:
            if not target_path.is_file() or target_path.read_text(encoding="utf-8") != expected:
                target_path.write_text(expected, encoding="utf-8")
                print(f"wrote {target_path.relative_to(root)}")

    generated_names = {name for name, _ in skills}
    if dst.is_dir():
        for existing in dst.glob("*.md"):
            base = existing.stem
            if base == "README":
                continue
            if base not in generated_names:
                if check_only:
                    stale.append(f"orphan:{base}")
                else:
                    existing.unlink()
                    print(f"removed orphan {existing.relative_to(root)}")

    if check_only:
        if stale:
            print(
                "knowledge/skills/ is out of sync with app/src/main/assets/skills/. "
                "Run `python mcp-server/scripts/sync_skills.py` and commit.",
                file=sys.stderr,
            )
            for s in stale:
                print(f"  - {s}", file=sys.stderr)
            return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync SKILL.md playbooks into knowledge/skills/.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify knowledge/skills/ is up to date; exit non-zero if not.",
    )
    args = parser.parse_args()
    return sync(check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
